### ISSUE TITLE
Documentation: OPEN ($C8) conflicting info on ref_num parameter size

### ISSUE THREAD

**Issue by micahcowan** [ProDOS-8/ProDOS-8.github.io#31]
The description of **OPEN ($C8)** at https://prodos8.com/docs/techref/calls-to-the-mli/#4.5.1 has conflicting info concerning the size of the 3rd parameter, **ref_num**. The ASCII octet diagram indicates that **ref_num** takes up a single byte (so, 5 bytes total as params to OPEN), but under the textual **Parameters** section below, it shows it as **ref_num (2-byte result)**.Incidentally, this exact documentation contradiction exists in Apple's original ProDOS 8 Technical Reference Manual, so I assume that's where your site acquired it. :)

**Update**: I've tried to follow the site guidelines/video on opening an issue, however it did not provide me the options pictured in the video for "Labels" and "Projects" during issue creation, and while those sidebars *do* appear now when I'm editing the issue, there are no gear-wheels next to the labels, and no apparent facility for making any selections for them. Perhaps they're only available to project developers, some roles have been altered, or else Github recently changed something related?

**Comment by DevoKun** [comment]
Thank you for pointing out this issue, @micahcowan .
You are correct, the site contains the original techref from Apple.
It would be a great help, if you are willing and able, to create a code update and submit a pull request for the content correction.
If you are unable to make a pull request I will work with you to get the content updated appropriately.
Thank you for your interest in ProDOS-8.
