### ISSUE TITLE
SmartPort technical notes missing

### ISSUE THREAD

**Issue by tjboldt** [ProDOS-8/ProDOS-8.github.io#39]
Technical Note 21 contains a link to SmartPort Technical Note 4 but this gives a 404 error.

This page:
https://prodos8.com/docs/technote/21/

Links to this missing page:
https://prodos8.com/docs/technote/smpt/tn.smpt.4.html

**Comment by DevoKun** [comment]
Added the missing technotes and updated the urls's accordingly.

**Comment by tjboldt** [comment]
Thanks for the same-day fix!
