### ISSUE TITLE
Disk images fail to download due to mixed content

### ISSUE THREAD

**Issue by inexorabletash** [ProDOS-8/ProDOS-8.github.io#43]
Repro:

1. Visit https://prodos8.com/releases/prodos-243/ in Chrome (tested in Windows 120.0.6099.199)
2. Open devtools (menu > more tools > developer tools)
3. In devtools, click on the Console tab
4. On the page, click Download ProDOS 2.4.3

Expected:

Disk image downloads. 

Actual:

Download blocked, console reports:

> Mixed Content: The site at 'https://prodos8.com/' was loaded over a secure connection, but the file at 'http://prodos8-releases.s3-website-us-east-1.amazonaws.com/ProDOS_2_4_3.po' was loaded over an insecure connection. This file should be served over HTTPS. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

Root cause:

Disk image is served from an HTTP endpoint, not HTTPS endpoint, which modern browsers forbid. (Because it means the user is downloading a resource that could be tampered with in flight, defeating the security assertions of the page served over HTTPS.)

Fix:

Serve from an HTTPS endpoint instead. 

(Note that the 2.4.1 and 2.4.2 pages serve the image from HTTPS and so aren't affected.)

**Comment by inexorabletash** [comment]
Fix: Update the link to be the correct S3 Object URL for the resource

https://prodos8-releases.s3.amazonaws.com/ProDOS_2_4_3.po

(you can find this on the object's page in the S3 console)

**Comment by DevoKun** [comment]
resolved
